config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :places do
    resources :bookings, except: [:index, :destroy] do
      get 'confirmation', to: 'bookings#confirmation', as: :confirmation
    end
    resources :reviews, only: :create
  end


  get 'bookings', to: 'bookings#index', as: :bookings
  resources :bookings, only: :destroy

  # delete "reviews/:id", to: "reviews#destroy"
  resources :reviews, only: :destroy

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :place

  validates :guests, :date, presence: true
end

app/models/place.rb
class Place < ApplicationRecord

  CATEGORIES = ['Afterwork', 'Diner', 'Before Midnight', 'All Night Long']
  belongs_to :user
  has_many :bookings
  has_many :reviews, dependent: :destroy
  validates :name, :address, :description, :guest_capacity, :price, presence: true
  validates :party_type, inclusion: { in: CATEGORIES }
  mount_uploader :photo, PhotoUploader
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :place
  validates :content, length: { minimum: 20 }
  validates :note, :inclusion => 0..5
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :bookings
  has_many :places
  mount_uploader :photo, PhotoUploader
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  # pundit
  # include Pundit
  # # Pundit: white-list approach.
  # after_action :verify_authorized, except: :index, unless: :skip_pundit?
  # after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :photo, :photo_cache, :description])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
    before_action :booking_find, only: [:show, :edit, :update ]

  def index
    @user = current_user
    @bookings = Booking.where(user_id: current_user.id)
  end

  def new
    @booking = Booking.new
    @place = Place.find(params[:place_id])
  end

  def create
    @booking = Booking.new(booking_params)
    @place = Place.find(params[:place_id])
    @booking.place = @place
    @booking.user = current_user
    # @booking.date = Date.parse(params[:booking][:date])
    if @booking.save
      redirect_to bookings_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @booking.update
      redirect_to bookings_path
    else
      render :edit
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to bookings_path
  end

def confirmation
@booking = Booking.find(params[:booking_id])
end

  private

  def booking_params
    params.require(:booking).permit(:guests, :date, :booking_type)
  end

  def booking_find
    @booking = Booking.find(params[:booking_id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :place_find, only: [:show, :edit, :update, :destroy]

  def index
    @map_flag = 'index'
    if params[:query].present?
      @query = params[:query]
      if Place.where.not(latitude: nil, longitude: nil)
        @places = Place.where("name iLike '%#{params[:query]}%'")
        @markers = @places.map do |place|
      {
        lat: place.latitude,
        lng: place.longitude,
         infoWindow: render_to_string(partial: "infowindow", locals: { place: place })
      }
        end
      end
    else
      @places = Place.where.not(latitude: nil, longitude: nil)
      @markers = @places.map do |place|
      {
        lat: place.latitude,
        lng: place.longitude,
        infoWindow: render_to_string(partial: "infowindow", locals: { place: place }),
        # image_url: helpers.asset_url('REPLACE_THIS_WITH_YOUR_IMAGE_IN_ASSETS')
      }
      end
    end
  end

  def show
    @map_flag = 'show'
  gon.dates = @place.bookings.map { |booking| booking.date.to_s }
  @review = Review.new
  @booking = Booking.new
    # if Place.where.not(latitude: nil, longitude: nil)

      # @place = Place.where.not(latitude: nil, longitude: nil)
    @markers = [{
      lat: @place.latitude,
      lng: @place.longitude,
      infoWindow: render_to_string(partial: "infowindow", locals: { place: @place }),
    }]
  end

  # end

  def new
    @place = Place.new
  end

  def create
    @place = Place.new(place_params)
    @place.user = current_user
    if @place.save
      redirect_to place_path(@place)
    else
      render :new
    end
  end

  # def show
  #   @review = Review.new
  # end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def place_params
    params.require(:place).permit(:address, :party_type, :name, :description, :guest_capacity, :price, :photo, :lattitude, :longitude)
  end

  def place_find
    @place = Place.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @place = Place.find(params[:place_id])
    @review = Review.new(review_params)
    @review.place = @place
    if @review.save
      respond_to do |format|
        format.html { redirect_to place_path(@place) }
        format.js  # <-- will render `app/views/reviews/create.js.erb`
      end
    else
      respond_to do |format|
        format.html { render 'places/show' }
        format.js  # <-- idem
      end
    end
  end

  def destroy
      @review = Review.find(params[:id])
      @review.destroy
      respond_to do |format|
        format.html { render 'places/show' }
        format.js
      end
  end

  private

  def review_params
    params.require(:review).permit(:content, :note)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
    <%= simple_form_for [ @place, @booking ] do |f| %>
      <%= f.input :guests, collection: 1..100, prompt: "Combien serez-vous?", selected: 10, error: "Veuillez nous indiquer combien vous serez" %>
      <%= f.input :date, as: :string, required: false, input_html: {class: "datepicker"} %>
      <%= f.button :submit, "Book now!", class: "btn btn-primary" %>
    <% end %>

app/views/bookings/confirmation.html.erb
<div class="container">
<h2>Thanks for booking <%= @booking.place.name %></h2>
<p><strong>Your place summary: </strong></p>
<br>
<p><%= @booking.place.description %></p>

</div>

app/views/bookings/index.html.erb
<div class="container">
 <br>
  <h1 id= "book-titles">Vos bookings </h1>
  <br>
  <br>
  <% @bookings.last(4).each do |booking| %>
    <div class="card-trip mb-4">
    <img src="<%= booking.place.photo %>">
    <div class="card-trip-infos">
      <%= link_to "Cancel", booking_path(booking), method: :delete, class:"btn btn-danger m-4" %>
      <%= link_to "View Place", place_path(booking.place), class:"btn btn-outline-success m-4" %>

      <div>
        <h2>Votre prochain <%= booking.place.party_type %> à <%= booking.place.name %></h2>
        <p>Rendez-vous le: <%= booking.date %></p>
      </div>
      <h2 class="card-trip-pricing"><%= booking.place.price %>€ / nuit</h2>
      <img src='<%= current_user.photo %>' class="card-trip-user avatar-bordered"/>
    </div>
    </div>
  <% end %>

  <br>
  <br>
  <h1 id= "book-titles">Vos Appartements </h1>
  <br>
  <br>
  <% current_user.places.each do |place| %>
    <div class="card-product m-4">
      <img src="<%= place.photo %>">
      <div class="card-product-infos">
        <h2><%= place.name %></h2>
        <p>Up to <%= place.guest_capacity %> guests.</p>
        <p><%= place.price %>€ / nuit.</p>
        <%= link_to "edit", edit_place_path(place), class:"btn btn-outline-warning" %>
      </div>
    </div>
  <% end %>
<%= link_to "add an appartement", new_place_path, class:"btn btn-outline-warning m-4" %>
</div>

app/views/bookings/new.html.erb
<h1>booking new</h1>
<div class="container">
 <%= render 'bookings/form', place: @place, booking: @booking %>


  </div>
</div>

  <%#= render 'form', booking: @booking @place %>

app/views/bookings/show.html.erb
<h1>show booking</h1>

<div class="container">
  <div class="form-wrapper" style="width: 400px; margin: 0 auto;">
    <h2>Flatpickr Demo</h2>

    <%= simple_form_for :search, method: "get" do |f| %>
      <%= f.input :starts_at, as: :string, required: false, input_html: {class: "datepicker"} %>
      <%= f.input :ends_at, as: :string, required: false, input_html: {class: "datepicker"} %>
      <%= f.button :submit, "Go", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v1.0.0/mapbox-gl.css' rel='stylesheet' />
    <title>Enjoy your evening drinks in the top flats in the world  </title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <%= include_gon %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= render 'shared/flashes' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <% if params[:action] != "home" %>
    <%= render 'shared/footer'  %>
    <% end %>

    <script src='https://api.tiles.mapbox.com/mapbox-gl-js/v1.0.0/mapbox-gl.js'></script>
  </body>
</html>

app/views/pages/home.html.erb
      <!-- banner -->

<div class="homepage-content-container">
  <div class="homepage-content row align-items-center">
    <div class="homepage-content-title">
      <h1>Afterwork, dîners, matchs, <br> dans des appartements insolites à Paris.</h1>
      <div class="mt-4" id="avis-home">
        <div class="ms-slider">
          <ul class="ms-slider__words">
            <li class="ms-slider__word">"Psg sur écran géant! ⚽"</li>
            <li class="ms-slider__word">"Incroyable dîner en amoureux 🥂"</li>
            <li class="ms-slider__word">"Mes 30 ans sur un Rooftop. 😍"</li>
            <!-- This last word needs to duplicate the first one to ensure a smooth infinite animation -->
            <li class="ms-slider__word">"Psg sur écran géant! ⚽"</li>
          </ul>
        </div>
        <div class="mt-4 d-flex flex-row-reverse"id="cta">
          <a href="<%= places_path %>">Découvrir</a>
      </div>
    </div>
  </div>
</div>



<video id="target-source" playsinline="playsinline" autoplay="autoplay" muted="muted" loop="loop">
  <source src="https://v.ftcdn.net/01/04/96/48/700_F_104964807_BdVT8FsfUHakibMCPDVtDVFPnnndzZ80_ST.mp4" type="video/mp4">
</video>




<script>
     var links = ['https://v.ftcdn.net/01/94/29/41/700_F_194294173_xBKpbwDJ91ekEkCC2PTkbkr2KtQWacaN_ST.mp4', 'https://v.ftcdn.net/01/16/28/37/700_F_116283741_EfYkiZQc4An9dOMs7ZfcCTAZlcriA5yF_ST.mp4'];
     var i = 0;
     var renew = setInterval(function(){
         if(links.length == i){
             i = 0;
         }
         else {
         document.getElementById("target-source").src = links[i];
         i++;

     }
     },5000);
</script>


<!--
<div class="video-container">
  <video autoplay muted loop>
    <source src="https://v.ftcdn.net/01/04/96/48/700_F_104964807_BdVT8FsfUHakibMCPDVtDVFPnnndzZ80_ST.mp4" type="video/mp4">
  </video>
  <div class="overlay-content">
    <h1>Prenez l'Apéro dans des appartements insolites</h1>
    <p>Afterwork - Dîner - Soirée Foot - All Over The Night</p>
    <%= link_to "découvrir les lieux", places_path, class:"btn btn-light" %>
  </div>

  <div class="location">
    <p><i class="fas fa-compass"></i> Villa Gaudelet, Paris 11ème</p>
  </div>
</div>

</div>
 -->

app/views/places/_form.html.erb
  <%= simple_form_for (@place) do |f|  %>
  <%= f.input :name, error: "please give the best summary of your flat ", placeholder: "Dream flat in Paris" %>
  <%= f.input :description, error: "please describe your flat", placeholder: "Beautyfull house in the middle of..." %>
  <%= f.input :address, error: "please give us a valid address", placeholder: "16, rue gaudelet, Paris" %>
  <%= f.input :party_type, collection: Place::CATEGORIES, error: "please select at least 1 choice", placeholder: "Pick from the list" %>
  <%= f.input :guest_capacity, collection: 1..100, prompt: "Select your age", selected: 20, error: "please pick the amount of guest you are planning to be" %>
  <%= f.input :price, placeholder: "Please give us a valid addressat would be your price for a night?" %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.button :submit, "add your Appartment", class: "btn btn-primary" %>

<% end %>

app/views/places/_infowindow.html.erb
<% if @map_flag == 'index' %>
  <div class="card-trip">
    <img src='<%= place.photo %>'>
    <div class="card-trip-infos">
      <div>
        <h2 class="mb-0"><%= place.name %></h2>
        <p><%= place.description.first(30) %>...</p>
      </div>

      <img src='<%= place.user.photo %>' class="card-trip-user avatar-bordered"/>
    </div>
    <div><%= render 'shared/stars' %></div>
    <div>€ <%= place.price %>
        <%= link_to "Book Now", place_path(place), class:"btn btn-outline-primary btn-sm" %>
    </div>
  </div>
<% elsif @map_flag == 'show' %>
  <%= place.address %>
<% end %>

app/views/places/edit.html.erb
  <div class="container mt-4">
    <div class="row">
      <div class="col-6 m-auto">
        <div class="place-form">
          <h1>Mettez à jour vos informations</h1>
          <div class="mt-3">
            <%= render 'form', place: @place %>
            <%= link_to "Back", places_path, class:"btn btn-light" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/places/index.html.erb
<div class="place-container mt-3">

  <!-- query -->


  <div class="ml-auto flex">
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" name="query" type="search" placeholder="Search" aria-label="Search" value="<%= params[:query] %>">
      <div id="cta">
        <button type="submit">Chercher</button>
      </div>
    </form>
  </div>


  <!--   Results query -->

  <div class="row mt-3">
    <div class="col result-query">
      <p>Vous avez cherchez <strong><%= params[:query] %></strong>. Nous avons trouvé <strong><%= @places.count %></strong> résultats sur un total de <strong><%= Place.count %></strong> lieux sur notre plateforme.</p>
    </div>
  </div>


  <!-- Display cards  -->

  <% if  @places.count <= 8 %>
    <div class="row">
      <% @places.each do |place| %>
        <div class="col-3 px-2">
          <%= link_to place_path(place) do %>
            <div class="place-card">
              <div class="place-card-image" style="background-image: url('<%= place.photo %>')"></div>
              <div class="place-card-content pt-2">
                <div class="place-card-title d-flex align-items-center mb-0 pb-0">
                  <h4><%= place.name.upcase %></h4>
                  <span class="point px-1 pb-2"> · </span>
                  <h4>PARIS 11</h4>
                </div>
                <p class="mb-0"><%= place.name %></p>
                <div class="place-card-votes d-flex justify-content-start pt-1">
                  <%= render 'shared/stars' %>
                  <div class="votes pl-1 d-flex justify-content-start">
                    <p>110</p>
                    <span class="point px-1 pb-2"> · </span>
                    <p>SuperApéro</p>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  <% else  %>
    <div class="row">
      <% @places.first(8).each do |place| %>
        <div class="col-3 px-2">
          <%= link_to place_path(place) do %>
            <div class="place-card">
              <div class="place-card-image" style="background-image: url('<%= place.photo %>')"></div>
              <div class="place-card-content pt-2">
                <div class="place-card-title d-flex align-items-center mb-0 pb-0">
                  <h4><%= place.name.upcase %></h4>
                  <span class="point px-1 pb-2"> · </span>
                  <h4>PARIS 11</h4>
                </div>
                <p class="mb-0"><%= place.name %></p>
                <div class="place-card-votes d-flex justify-content-start pt-1">
                  <%= render 'shared/stars' %>
                  <div class="votes pl-1 d-flex justify-content-start">
                    <p>110</p>
                    <span class="point px-1 pb-2"> · </span>
                    <p>SuperApéro</p>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>

  <div
    id="map"
    style="width: 100%;
    height: 600px;
    position: relative"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>


    <!-- our selection -->

  <div class=" mt-3 mb-3">
    <div class="row px-2">
      <div class="banner-index col-12" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://res.cloudinary.com/dpnte3nr8/image/upload/q_auto/v1559044107/adam-wilson-138927-unsplash_v5hjyn.jpg);">
        <div class="banner-index-container">
          <h1>Retrouvez la sélection de l'équipe</h1>
          <p>Des lieux testés et approuvés, pour passer les meilleurs apéros de votre vie de parisien.</p>
          <a href="#">Commencer</a>
        </div>
      </div>
    </div>
  </div>


    <!--   others places -->


  <div class=" mt-3">
    <div class="row">
      <% @places[8..@places.length].each do |place| %>
        <div class="col-3 px-2">
          <%= link_to place_path(place) do %>
            <div class="place-card">
              <div class="place-card-image" style="background-image: url('<%= place.photo %>')"></div>
              <div class="place-card-content pt-2">
                <div class="place-card-title d-flex align-items-center mb-0 pb-0">
                  <h4><%= place.name.upcase %></h4>
                  <span class="point px-1 pb-2"> · </span>
                  <h4>PARIS 11</h4>
                </div>
                <p class="mb-0"><%= place.name %></p>
                <div class="place-card-votes d-flex justify-content-start pt-1">
                  <%= render 'shared/stars' %>
                  <div class="votes pl-1 d-flex justify-content-start">
                    <p>110</p>
                    <span class="point px-1 pb-2"> · </span>
                    <p>SuperApéro</p>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/places/new.html.erb
  <div class="container mt-4">
    <div class="row">
      <div class="col-6 m-auto">
        <div class="place-form">
          <h1>Ajouter un lieu</h1>
          <div class="mt-3">
            <%= render 'form', place: @place %>
            <%= link_to "Back", places_path, class:"btn btn-light" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/places/show.html.erb
<div class="map" style="background-image: url('<%= @place.photo %>')"></div>

<div class="container margin-top-negative">
  <div class="row">
    <div class="col-8">
      <div class="place-show-card">
        <h1><%= @place.name %></h1>
        <p class="place-show-address"><%= @place.address %></p>
      </div>
      <div class="place-show-card">
        <h3>A bit more about this place...</h3>
        <p><%= @place.description %></p>
          <div
            id="map"
            style="width: 100%;
            height: 600px;"
            data-markers="<%= @markers.to_json %>"
            data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
        ></div>
      </div>

    </div>

    <div class="col-4">
      <div class="place-show-card">
        <h5>Book this Place!</h5>
        <%= render 'bookings/form', place: @place, booking: @booking %>

      </div>
      <div class="place-show-card">
        <h3>Details</h3>
        <div class="flex">
          <div class="flex">
            <i class="material-icons mr-2">people</i><span><%= @place.guest_capacity %></span>
          </div>
          <div class="flex ml-3">
            <i class="material-icons mr-2">euro_symbol</i> <%= @place.price %>
          </div>
        </div>
      </div>

      <div class="place-show-card">

          <!--       test ajax -->
                <h4>
                  <%= pluralize @place.reviews.size, "review" %>
                </h4>
          <!--       review -->

                <div id="reviews">
                  <% if @place.reviews.blank? %>
                    Soyez le premier à laisser une note sur <%= @place.name %>
                  <% else %>
                    <% @place.reviews.each do |review| %>
                      <%= render 'reviews/show', review: review %>
                    <% end %>
                  <% end %>
                </div>

                <!-- formulaire -->

                <%= render 'reviews/form', place: @place, review: @review %>

      </div>


      <div class="place-show-card">
        <div class="flex-align">
          <h6 class="no-mb">Share</h6>

          <div class="flex">
            <i class="fa fa-facebook-square fa-2x mr-2"></i>
            <i class="fa fa-twitter-square fa-2x mr-2"></i>
            <i class="fa fa-pinterest-square fa-2x mr-2"></i>
            <i class="fa fa-envelope-square fa-2x"></i>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/reviews/_form.html.erb
<%= simple_form_for([ place, review ], remote: true) do |form| %>
  <%= form.input :content, as: :text %>
  <%= form.input :note, as: :integer %>
  <%= form.button :submit %>
<% end %>

app/views/reviews/_show.html.erb
<div id=<%= review.id  %>>
  <p><%= review.content %></p>
  <p><%= review.note %></p>
  <%= link_to "Delete", review, method: :delete, remote: true, "data-review-id": review.id %>
</div>

app/views/reviews/create.js.erb
function refreshForm(innerHTML) {
  const newReviewForm = document.getElementById('new_review');
  newReviewForm.innerHTML = innerHTML;
}

function addReview(reviewHTML) {
  const reviews = document.getElementById('reviews');
  reviews.insertAdjacentHTML('beforeend', reviewHTML);
}

<% if @review.errors.any? %>
  refreshForm('<%= j render "reviews/form", place: @place, review: @review %>');
<% else %>
  addReview('<%= j render "reviews/show", review: @review %>');
  refreshForm('<%= j render "reviews/form", place: @place, review: Review.new %>');
<% end %>

app/views/reviews/destroy.js.erb
document.getElementById("<%= @review.id %>")
  .remove();

app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> by pilou
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%#= image_tag "apphero.jpg" , class: "rounded ml-4" %>
    <% if params[:action] == "home" %>
    <%= cl_image_tag("logo-pilou-white_ezn2gi", :transformation => { :width => 55 })%>
    <% else %>
    <%= cl_image_tag("logo-pilou-blue_xwxgcy", :transformation => { :width => 55 })%>
    <% end %>
    <% end %>



  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%#= link_to "Home", root_path, class: "nav-link" %>
        </li>
<!--         <li class="nav-item">
          <%#= link_to "Vos appartements", bookings_path, class: "nav-link" %>
          <p class="nav-item"><span id="banner-typed-text"></span></p>
        </li> -->
        <li class="nav-item dropdown">
          <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle mr-4", id: "navbarDropdown", data: { toggle: "dropdown" }, :transformation=>[{:width=>400, :height=>400, :gravity=>"face", :radius=>"max", :crop=>"crop"},{:width=>200, :crop=>"scale"}], :border => { :width => 2, :color => 'white' },'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Vos appartements", bookings_path, class: "dropdown-item" %>
            <%= link_to "Vos réservations", bookings_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>